language: python
python:
- '3.6'
- '3.7'

compiler:
  - gcc

env:
  NUMBA_DISABLE_JIT=1 MULTINEST_TAG=v3.10 WITHMPI=no
  
before_install:
  - sudo apt-get install -qq libblas{3,-dev} liblapack{3,-dev} libatlas{3-base,-dev} cmake build-essential git gfortran
    # Install and test
  - git clone --branch ${MULTINEST_TAG} https://github.com/JohannesBuchner/MultiNest
  - mkdir -p MultiNest/build; pushd MultiNest/build; cmake .. && make && popd
  - export LD_LIBRARY_PATH=MultiNest/lib/:${LD_LIBRARY_PATH} 
  

install:
- pip install --upgrade pytest pytest-cov codecov numpy>=1.16 cython
- python setup.py install

script:
- luigid --background --logdir . --state-path . 
- python -m pytest -vv --cov=gbm_bkg_pipe/
